// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRRFWU5WdSXR09yW_V6XxtuvCk6pJsh4',
    appId: '1:89303463741:web:ab9b40d32679a010ed7754',
    messagingSenderId: '89303463741',
    projectId: 'karaoke-real-one',
    authDomain: 'karaoke-real-one.firebaseapp.com',
    databaseURL: 'https://karaoke-real-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karaoke-real-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7wjOzvJwlUuxHGMvBA60TR-ymWg8H_dQ',
    appId: '1:89303463741:android:17debe0d9a7b4601ed7754',
    messagingSenderId: '89303463741',
    projectId: 'karaoke-real-one',
    databaseURL: 'https://karaoke-real-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karaoke-real-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA53vLt8jOvdWKoBMa75q1vJjRMLeYap4A',
    appId: '1:89303463741:ios:de53380eedb90f80ed7754',
    messagingSenderId: '89303463741',
    projectId: 'karaoke-real-one',
    databaseURL: 'https://karaoke-real-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karaoke-real-one.appspot.com',
    iosClientId: '89303463741-nuooe89h7petaocf77i2g3n6pnk3h4sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.karaokeRealOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA53vLt8jOvdWKoBMa75q1vJjRMLeYap4A',
    appId: '1:89303463741:ios:de53380eedb90f80ed7754',
    messagingSenderId: '89303463741',
    projectId: 'karaoke-real-one',
    databaseURL: 'https://karaoke-real-one-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'karaoke-real-one.appspot.com',
    iosClientId: '89303463741-nuooe89h7petaocf77i2g3n6pnk3h4sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.karaokeRealOne',
  );
}
